include:
  - compose.broker.yml

services:
  # broker de message
  broker:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    user: 1000:1000
    volumes:
      - ./broker/mnt/config:/mosquitto/config:ro
      - ./broker/mnt/data:/mosquitto/data:rw
    ports: 
      - 8080:8080
  # validation d'un fichier de métadonnées
  validate-metadata:
    build: ./scripts
    container_name: validate-metadata
    volumes:
      - ./data:/data:ro
    command: >
      sh -c "python3 /app/validate-metadata-message-pywcmp.py /data/fr-ifremer-argo-core-metadata.json"
  # validation message pour le fichier de métadonnées
  validate-metadata-message:
    build: ./scripts
    container_name: validate-metadata-message
    environment:
      PYWIS_PUBSUB_GDC_URL: https://api.weather.gc.ca/collections/wis2-discovery-metadata
    volumes:
      - ./data:/data:ro
    command: >
      sh -c "python3 /app/validate-data-message-pywis-pubsub.py /data/coriolis-msg-argo-metadata-notification.json"
    depends_on:
      validate-metadata:
        condition: service_completed_successfully
  # publication du contenu du fichier métadonnées
  publish-metadata-message:
    build: ./scripts
    container_name: publish-metadata-message
    volumes:
      - ./data:/data:ro
    command: >
      sh -c "python3 /app/publish-notification-message.py origin/a/wis2/fr-ifremer-argo /data/coriolis-msg-argo-metadata-notification.json"
    environment:
      MQTT_BROKER_DOMAIN: broker
      MQTT_BROKER_PORT: 8080
      MQTT_USERNAME: wis2-argo-rw
      MQTT_PASSWORD: wis2-argo-rw
      MQTT_BROKER_TOPIC_SUB: origin/a/wis2/fr-ifremer-argo/metadata
      MQTT_BROKER_TOPIC_PUB: origin/a/wis2/fr-ifremer-argo/metadata
    depends_on:
      broker:
        condition: service_started
      validate-metadata-message:
        condition: service_completed_successfully
